---
title: "Trevor Nishida's CV"
author: Trevor Nishida
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For pipe function
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode a few little dots are unaligned; implement a fix with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year.
# datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
# If printing PDF link to HTML and if printing HTML link location of PDF on Github
if(params$pdf_mode){
  cat("View this CV online, anytime at _trevornishida.com/cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/trevornishida/cv/raw/main/NishidaTrevor_CV.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
# Add contact information
CV %>% print_contact_info()
```

```{r}
## CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

Source code is available on [github.com/trevornishida/cv](https://github.com/trevornishida/cv/).

Last updated on `r Sys.Date()`.



Main
================================================================================

Trevor Nishida {#title}
--------------------------------------------------------------------------------

```{r}
# Add special double pipe so we modify the CV object in place
# CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_exp')
```

Pertinent Skills {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('skills')
```



```{r}
CV %<>% print_links()
```

